  test_rce: !!python/object/apply:time.sleep [10]

  queue_rules:
    - name: default
      queue_conditions: []
      merge_conditions: []

  pull_request_rules: []

  merge_protections_settings:
    reporting_method: check-runs
