queue_rules:
  - name: default
    merge_conditions:
      - status-success=spoof-check
    merge_method: merge
pull_request_rules:
  - name: q
    conditions: [label=ready]
    actions:
      queue: {name: default}
